id: Majestic Million Test Playbook
version: -1
name: Majestic Million Test Playbook
fromversion: 5.5.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d173c680-187c-4e6b-801c-9eb299fb4101
    type: start
    task:
      id: d173c680-187c-4e6b-801c-9eb299fb4101
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: f648f896-76f5-443f-871a-16e00f7164b3
    type: regular
    task:
      id: f648f896-76f5-443f-871a-16e00f7164b3
      version: -1
      name: majesticmillion-get-indicators
      description: Gets the feed indicators.
      script: '|||majesticmillion-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      limit:
        simple: "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: d9d3a364-d163-4b5f-8f70-0877816d6479
    type: title
    task:
      id: d9d3a364-d163-4b5f-8f70-0877816d6479
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
